server:
  port: 50000

spring:
  application:
    name: gulimall-seckill

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719      #端口配置会在应用对应的机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互
        dashboard: localhost:8333     #配置控制台信息

  redis:
    host: 192.168.138.102
    port: 6379

  task:
    execution:
      pool:
        core-size: 5    #异步任务核心线程数
        max-size: 50    #异步任务最大线程数

  session:
    store-type: redis

  rabbitmq:
    host: 192.168.138.102
    port: 5672
    virtual-host: /
    publisher-confirms: true    #开启发送端确认
    publisher-returns: true     #开启发送端消息抵达队列的确认
    template:
      mandatory: true         #只要抵达队列，以异步方式优先回调returnConfirm
    listener:
      simple:
        acknowledge-mode: manual  #手动确认消息

  thymeleaf:
    cache: false


#Sentinel Endpoint支持,加入spring-boot-starter-actuator依赖,添加配置,暴露的 endpoint 路径为 /actuator/sentinel
management:
  endpoints:
    web:
      exposure:
        include: "*"


