server:
  port: 12000
  servlet:
    session:
      timeout: 30m


spring:
  application:
    name: gulimall-search

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333     #配置控制台信息

  thymeleaf:
    cache: false

  redis:
    host: 192.168.138.102
    port: 6379

  session:
    store-type: redis

  zipkin:
    base-url: http://192.168.138.102:9411/ # zipkin 服务器的地址
    discoveryClientEnabled: false     # 关闭服务发现，否则 Spring Cloud 会把 zipkin 的 url 当做服务名称
    sender:
      type: web # 设置使用 http 的方式传输数据

  sleuth:
    sampler:
      probability: 1 # 设置抽样采集率为 100%，默认为 0.1，即 10%


logging:
  level:
    com.example.gulimall: error
    com.alibaba.nacos.client.naming: WARN
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug


#Sentinel Endpoint支持,加入spring-boot-starter-actuator依赖,添加配置,暴露的 endpoint 路径为 /actuator/sentinel
management:
  endpoints:
    web:
      exposure:
        include: "*"


#使用Sentinel来保护feign远程调用：熔断；
feign:
  sentinel:
    enabled: true