server:
  port: 11000


spring:
  application:
    name: gulimall-ware

  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.138.102:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333     #配置控制台信息
    alibaba:
      seata:
        tx-service-group:

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  rabbitmq:
    host: 192.168.138.102
    port: 5672
    virtual-host: /
    publisher-confirms: true    #开启发送端确认
    publisher-returns: true     #开启发送端消息抵达队列的确认
    template:
      mandatory: true         #只要抵达队列，以异步方式优先回调returnConfirm
    listener:
      simple:
        acknowledge-mode: manual  #手动确认消息


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


logging:
  level:
    com.example.gulimall: error
    com.alibaba.nacos.client.naming: WARN


#Sentinel Endpoint支持,加入spring-boot-starter-actuator依赖,添加配置,暴露的 endpoint 路径为 /actuator/sentinel
management:
  endpoints:
    web:
      exposure:
        include: "*"

